### ISSUE TITLE
error: could not find `publish-action@0.1.12` in registry `crates-io` with version `*`

### ISSUE THREAD

**Issue by konanzheng** [tu6ge/publish-action#1]
首先感谢您。这项工作帮我实现了自动发布到crates，真的很棒。
First of all, thank you. This work helped me achieve automatic publishing to crates, which was really great.
In the screenshot below is a little bit of a problem I encountered, if someone encounters it can also refer to
github action run failed on cargo install publish-action@0.1.12
i changed `cargo install publish-action@0.1.12` to `cargo install publish-action` on `publish.yam` file

![image](https://user-images.githubusercontent.com/3112689/172860061-ed9fabbd-192b-451d-b6ef-051fc2e89861.png)

**Comment by tu6ge** [comment]
Hi @konanzheng , this issue has been settled. 

这个问题已经修复

**Comment by tu6ge** [comment]
The specified version should still be installed, because it is not stable yet, and it is uncertain whether the future version will have destructive changes.
