### ISSUE TITLE
publish to private registries

### ISSUE THREAD

**Issue by rbtcollins** [tu6ge/publish-action#2]
This breaks today - I think but haven't checked that this is because the check for already published is bypassing the local index and instead probing crates.io directly (via SyncClient)

Better would be to attempt to resolve the crate through the cargo API I think. Perhaps https://doc.crates.io/contrib/apidoc/cargo/ops/registry/fn.wait_for_publish.html ?

**Comment by tu6ge** [comment]
Hi @rbtcollins, Usually, it runs on github action, If you need a local index, use the cargo command directly.

maybe, I didn't understand you. After all, my English level is limited.

**Comment by rbtcollins** [comment]
Hi. Yes I think there is a misunderstanding.

Cargo has a public registry: crates.io.
Cargo can also have private registries: https://doc.rust-lang.org/cargo/reference/registries.html#using-an-alternate-registry

To find out if an item is published in a private registry we can:
- use the cargo API
- use git to fetch the index and query in the index

Today publish-action uses a third option: make a call to crates.io, which is incompatible with private registry.

My proposal is to change 'check if version is published' to `use the cargo API`.
